server:
  port: 9090

jwt:
  secret: "your-very-secure-secret-key-that-is-long-enough" # (?? ??? ???? ? ?)
  expiration-ms: 3600000 # (1??)

spring:
  datasource:
    #driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:h2:mem:testdb
    url: jdbc:mysql://localhost:3306/notification_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: sa
    #password:
    username: root
    password: Rlawnsgk1!

  jpa:
    hibernate:
      # update: 엔티티에 맞춰 테이블을 자동 생성/수정함
      # validate: 엔티티와 테이블이 맞는지 검사만 함
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true



#  h2:
#    console:
#      enabled: true

logging:
  level:
    com.chosun.demoversion: DEBUG
